version: '2'
volumes:
  ${CLIENT}_wp_db:
    external: true
    driver: local
  ${CLIENT}_letsencrypt:
    external: true
    driver: local
  ${CLIENT}_wp_data:
    external: true
    driver: local
  ${CLIENT}_pydio:
    external: true
    driver: local
services:
  phpmyadmin:
    image: gabrielcossette/phpmyadmin-docker:dev
    links:
    - mysql:db
    labels:
      io.rancher.scheduler.affinity:host_label: Name=${CLIENT}
      io.rancher.container.pull_image: always
      Upgrade: phpmyadmin_dev
    environment:
      CONFIG_PASS: /run/secrets/${CLIENT}_PMA_PW
    secrets:
    - ${CLIENT}_PMA_PW      
  pydio:
    image: gabrielcossette/pydio-docker:dev
    environment:
      PGID: 82
      PUID: 82
      PYDIO_PASSWORD_FILE: /run/secrets/${CLIENT}_PW
      PYDIO_DB_HOST: mysql
      PYDIO_DB_NAME: pydio
      PYDIO_DB_USER: pydio
      PYDIO_DB_PASSWORD_FILE: /run/secrets/${CLIENT}_PYDIO_PW
    volumes:
    - ${CLIENT}_pydio:/data
    - ${CLIENT}_wp_data:/wp
    secrets:
    - ${CLIENT}_PW
    - ${CLIENT}_PYDIO_PW
    labels:
      io.rancher.scheduler.affinity:host_label: Name=${CLIENT}
      io.rancher.container.pull_image: always
      Upgrade: pydio_dev
  nginx:
    image: gabrielcossette/nginx-ee-docker:dev
    environment:
      POST_MAX_SIZE: 2G
      SITE: ${WP_URL}
      WP_CONTAINER_NAME: wordpress
      CACHE: redis
    volumes:
    - ${CLIENT}_wp_data:/var/www/html
    labels:
      io.rancher.scheduler.affinity:host_label: Name=${CLIENT}
      io.rancher.container.pull_image: always
      Upgrade: nginx_dev
  wordpress:
    image: gabrielcossette/wordpress-docker:dev
    environment:
      USER_FILE: /run/secrets/WP_User
      PASS_FILE: /run/secrets/WP_Pass
      SITE: https://${WP_URL}
      EMAIL: ${WP_EMAIL}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/${CLIENT}_WP_PW
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_SERVER: ${EMAIL_SERVER}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PW_FILE: /run/secrets/${CLIENT}_Email_PW
    volumes:
    - ${CLIENT}_wp_data:/var/www/html
    secrets:
    - WP_User
    - WP_Pass
    - ${CLIENT}_Email_PW
    - ${CLIENT}_WP_PW
    labels:
      io.rancher.scheduler.affinity:host_label: Name=${CLIENT}
      io.rancher.container.pull_image: always
      Upgrade: wordpress_dev
  LB:
    image: rancher/lb-service-haproxy:v0.7.15
    ports:
    - 80:80/tcp
    - 443:443/tcp
    - 2222:2222/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.affinity:host_label: Name=${CLIENT}
      io.rancher.container.pull_image: always
  mysql:
    image: gabrielcossette/mariadb-docker:dev
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/DB_Root
      MYSQL_DATABASE_WP: wordpress
      MYSQL_DATABASE_PYDIO: pydio
      MYSQL_DATABASE_PMA: phpmyadmin
      MYSQL_USER_ADMIN: admin
      MYSQL_USER_WP: wordpress
      MYSQL_USER_PYDIO: pydio
      MYSQL_USER_PMA: phpmyadmin
      MYSQL_PASSWORD_ADMIN_FILE: /run/secrets/${CLIENT}_PW
      MYSQL_PASSWORD_WP_FILE: /run/secrets/${CLIENT}_WP_PW
      MYSQL_PASSWORD_PYDIO_FILE: /run/secrets/${CLIENT}_PYDIO_PW
      MYSQL_PASSWORD_PMA_FILE: /run/secrets/${CLIENT}_PMA_PW
    volumes:
    - ${CLIENT}_wp_db:/var/lib/mysql
    secrets:
    - ${CLIENT}_PW
    - ${CLIENT}_WP_PW
    - ${CLIENT}_PYDIO_PW
    - ${CLIENT}_PMA_PW
    - DB_Root
    labels:
      io.rancher.scheduler.affinity:host_label: Name=${CLIENT}
      io.rancher.container.pull_image: always
      Upgrade: mysql_dev
  mysql-backup:
    image: gabrielcossette/backup-all-mysql:dev
    environment:
      BACKUP_INTERVAL: 86400
      BACKUP_FIRSTDELAY: 60
    links:
    - mysql
    restart: always
    volumes:
    - /root/backup:/var/dbdumps
    - /etc/localtime:/etc/localtime
    - /etc/timezone:/etc/timezone
    secrets:
    - DB_Root
    labels:
      io.rancher.scheduler.affinity:host_label: Name=${CLIENT}
      io.rancher.container.pull_image: always
      Upgrade: mysql-backup_dev
  sftp:
    image: gabrielcossette/sftp-docker:dev
    environment:
      USER: admin
      PASS_FILE: /run/secrets/${CLIENT}_PW
      UID: 82
    volumes:
    - ${CLIENT}_wp_data:/home/admin/wp
    secrets:
    - ${CLIENT}_PW
    command:
    - admin::82
    labels:
      io.rancher.scheduler.affinity:host_label: Name=${CLIENT}
      io.rancher.container.pull_image: always
      Upgrade: sftp_dev
  letsencrypt:
    image: janeczku/rancher-letsencrypt:v0.5.0
    environment:
      API_VERSION: Production
      AWS_ACCESS_KEY: ''
      AWS_SECRET_KEY: ''
      AZURE_CLIENT_ID: ''
      AZURE_CLIENT_SECRET: ''
      AZURE_RESOURCE_GROUP: ''
      AZURE_SUBSCRIPTION_ID: ''
      AZURE_TENANT_ID: ''
      CERT_NAME: ${CLIENT}
      CLOUDFLARE_EMAIL: ''
      CLOUDFLARE_KEY: ''
      DNSIMPLE_EMAIL: ''
      DNSIMPLE_KEY: ''
      DNS_RESOLVERS: 9.9.9.9:53
      DOMAINS: ${WP_URL}, db.${DOMAIN}, files.${DOMAIN}
      DO_ACCESS_TOKEN: ''
      DYN_CUSTOMER_NAME: ''
      DYN_PASSWORD: ''
      DYN_USER_NAME: ''
      EMAIL: ${WP_EMAIL}
      EULA: 'Yes'
      GANDI_API_KEY: ''
      OVH_APPLICATION_KEY: ''
      OVH_APPLICATION_SECRET: ''
      OVH_CONSUMER_KEY: ''
      PROVIDER: HTTP
      PUBLIC_KEY_TYPE: RSA-2048
      RENEWAL_PERIOD_DAYS: '20'
      RENEWAL_TIME: '12'
      VULTR_API_KEY: ''
    volumes:
    - /var/lib/rancher:/var/lib/rancher
    - ${CLIENT}_letsencrypt:/etc/letsencrypt
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.affinity:host_label: Name=${CLIENT}
      io.rancher.container.pull_image: always
  redis:
    image: gabrielcossette/redis-docker:dev
    labels:
      io.rancher.scheduler.affinity:host_label: Name=${CLIENT}
      io.rancher.container.pull_image: always
      Upgrade: redis_dev
